### ISSUE TITLE
Trailing comma in variadic call

### ISSUE THREAD

**Issue by otakubeam** [otakubeam/etude#3]
I should note, however, that the issue I had reported in telegram still persists even with the correct env var. I'll probably duplicate the report here as well:

Almost all tests fail, and I have tracked it down to qbe v1.1 not understanding the trailing comma in the construct `call $printf (l $strdata.0, ..., )`. The log message is `-:58: ) expected, got , instead`. It only seems to happen with the `...` in the arguments, as it doesn't complain about an earlier line with `call $cyclef3iPiPi ( w 40, l %.34, l %.35, )`.

_Originally posted by @abel1502 in https://github.com/otakubeam/etude/issues/1#issuecomment-1418205876_

**Comment by otakubeam** [comment]
@abel1502

I am afraid I can not reproduce the issue with **qbe** @ commit _f1b21d145ba03c6052b4b722dc457f8e944e6fca tag: v1.1_ and the following IL text (and bunch of small variations)

```
   function w $main() {
   @start
       call $printf(l 0, ...,)
   
   @end
       ret 0
   }
```

Could you compile qbe from scratch using the latest commit? 
https://c9x.me/git/qbe.git

**Comment by abel1502** [comment]
https fails (`Received HTTP/0.9 when not allowed`), but I have managed to clone it over git://. Now it does pass all tests except the two 10-shouldfail ones. I guess the tarball at qbe's site is outdated. Thanks!
